#cloud-config
#
# This is an example file to automatically configure resolv.conf when the
# instance boots for the first time.
#
# Ensure that your yaml is valid and pass this as user-data when starting
# the instance. Also be sure that your cloud.cfg file includes this
# configuration module in the appropriate section.
#

## Below is a Hack for MacOS & Multipass Issue
## Ref: https://discourse.ubuntu.com/t/troubleshooting-networking-on-macos/12901
write_files:
- encoding: b64
  content: ewogICJleGVjLW9wdHMiOiBbIm5hdGl2ZS5jZ3JvdXBkcml2ZXI9c3lzdGVtZCJdLAogICJsb2ctZHJpdmVyIjogImpzb24tZmlsZSIsCiAgImxvZy1vcHRzIjogewogICAgIm1heC1zaXplIjogIjEwMG0iCiAgfSwKICAic3RvcmFnZS1kcml2ZXIiOiAib3ZlcmxheTIiCn0K
  owner: root:root
  path: /etc/docker/daemon.json
  permission: 0644

users:
  - name: ubuntu
    ssh-authorized-keys:
      - <add local public key here>

runcmd:
  - cp /etc/netplan/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml.bak
  - sed -i -e '13i\\            nameservers:' /etc/netplan/50-cloud-init.yaml
  - sed -i -e '14i\\                addresses:\ [8.8.8.8, 8.8.4.4]' /etc/netplan/50-cloud-init.yaml
  - netplan apply
  - systemd-resolve --status | grep 'DNS Servers' -A2
  - DEBIAN_FRONTEND=noninteractive  apt-get update -y && apt-get upgrade -y
  - apt-get -y autoremove
  - apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get -y install docker-ce docker-ce-cli containerd.io
  - apt-get update && sudo apt-get install -y apt-transport-https curl
  - wget -q --show-progress --https-only --timestamping "https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-apiserver"
  - wget -q --show-progress --https-only --timestamping "https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-controller-manager"
  - wget -q --show-progress --https-only --timestamping "https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-scheduler"
  - wget -q --show-progress --https-only --timestamping "https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl"
  - chmod u+x kube-apiserver kube-controller-manager kube-scheduler kubectl
  - mv kube-apiserver kube-controller-manager kube-scheduler kubectl /usr/local/bin/
  - wget -q --show-progress --https-only --timestamping "https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz"
  - tar -xvf etcd-v3.3.9-linux-amd64.tar.gz
  - sudo mv etcd-v3.3.9-linux-amd64/etcd* /usr/local/bin/
  - sudo mkdir -p /etc/etcd /var/lib/etcd
